// @ts-check

const config = {
  title: "Use custom docker images in Truss",
  url: "https://rachfop.github.io",
  baseUrl: "/",
  organizationName: "rachfop",
  projectName: "custom-docker-image",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  
  plugins: [
    [
      'docusaurus-plugin-llms',
      {
        // Generate llms.txt file (summary of all docs)
        generateLLMsTxt: true,
        
        // Generate llms-full.txt file (full content of all docs)
        generateLLMsFullTxt: true,
        
        // Directory containing documentation files
        docsDir: 'docs',
        
        // Output directory for generated files (default: 'build')
        outputDir: 'build',
        
        // Include frontmatter in generated files (default: false)
        includeFrontMatter: false,
        
        // Custom file patterns to include (default: ['**/*.md', '**/*.mdx'])
        includePatterns: ['**/*.md', '**/*.mdx'],
        
        // Custom file patterns to exclude
        excludePatterns: ['**/node_modules/**', '**/build/**'],
        
        // Custom header for generated files
        customHeader: 'Generated by docusaurus-plugin-llms',
        
        // Whether to include table of contents in generated files
        includeTOC: true,
        
        // Custom separator between documents
        documentSeparator: '\n\n---\n\n',
      }
    ]
  ],

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/",
          sidebarPath: require.resolve("./sidebars.js"),
        },
        blog: false,
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      }),
    ],
  ],
};

module.exports = config;
